# Fuel and emissions properties
Name = "Jet-A"
Energy_MJ_per_kg = 43.2
EI_H2O            = 1233.3865 # gH2O/kgfuel
EI_CO2            = 3155.6 # gCO2/kgfuel
nvolCarbCont      = 0.95

# Sulfur content and sulfate yield
FSCnom            = 600.0    # gS/kgfuel
Epsnom            = 0.02     # fraction converted to sulfate