["General Information"]
ac_name = "B738"
engine = "CFM56-7B"
year = 2019                     # Required year (YYYY)
time_frequency = 'Y'            # Y/M/D/H

AC_class = NarrowbodyShortHaul   # 1. NarrowbodyShorthaul
                                # 2. WidebodyLonghaul
                                # OR ICAO code list: ['736', '737', '738']

max_range_nm = 2940.0           # 2940 for CFM56-7B and LEAP-1B, 7800 for GE90-115B

performance_model_input = "PerformanceModel"
                                # "OPF" : Input as BADA type OPF file
                                # "PTF" : Input as BADA type PTF file
                                # PerformanceModel : JSON file with state variables - fuel_flow = f(h, V, gamma, m_fuel)

performance_model_input_file = "./src/IO/default_performance_model.json" 

["LTO data"]
LTO_input_mode = "custom" # "custom" : custom LTO data file provided
                          # "EDB" : EDB datafile provided
LTO_input_file = "./src/IO/B738__.LTO"

["Scheduling"]
schedule_folder = "./src/scheduling/schedule_files/"
schedule_in_file = "2019pandas_processed_forAEIC_normal.csv"
airport file = "all_airports.csv"
stop_after_scheduling = true
reference_schedule = ""         # File name for existing schedule
                                # Empty string: Use OAG data and max range to get schedule
sample_schedule = false         # Sample schedule distribution to get smaller collection
sample_number = 1000            # If sample_schedule: how many flights for the sample

["OUTPUT"]
output_folder = "Emission_Files/"