# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Ruff (Lint & Style)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff

    # “ruff check .” performs linting;
    # “ruff format --check .” verifies Black-style formatting.
    - name: Run Ruff
      run: |
        ruff check .
        ruff format --check .

  tests:
    name: Pytest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.13"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install project & dependencies
      run: uv sync --locked --all-extras --dev

    - name: Set AEIC_DATA_DIR
      run: echo "AEIC_DATA_DIR=$(pwd)/data" >> "$GITHUB_ENV"

    - name: Run Pytest
      run: uv run pytest tests/ --cov --cov-branch --cov-report=term --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
